<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Thu, 2009-06-25 09:14
 * View: tenants
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   tenants, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $iid -- 
 * $iid_label -- The assigned label for $iid
 * $body -- Display the Main Content.
 * $body_label -- The assigned label for $body
 *
 * This function goes in your views-list-tenants.tpl.php file
 */
 
 
 //now we add the stylesheet...
  drupal_add_css(path_to_theme() .'/browertwo/tenants.css');
  
  ?>

<?php print $body?>

